-- =============================================================================
-- V15 — Auditoría de eliminación de cuenta (baja de usuario)
--
-- Tabla nueva y desacoplada de registro_auditoria_empleados (V-anteriores): esa
-- tabla exige un establecimiento no-nulo por fila (está pensada para acciones de
-- dueño/empleado dentro de un establecimiento) y no encaja para la baja de un
-- PLAYER o de un OWNER sin establecimientos. Ver spec de eliminación de cuenta
-- (docs/superpowers/specs/2026-08-15-eliminacion-cuenta-design.md).
-- =============================================================================

CREATE TABLE auditoria_eliminacion_usuario (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id   BIGINT NOT NULL,
    actor_id     BIGINT,
    tipo         VARCHAR(30) NOT NULL,
    detalle      VARCHAR(500),
    fecha_hora   TIMESTAMP NOT NULL,
    CONSTRAINT fk_auditoria_eliminacion_usuario_usuario
        FOREIGN KEY (usuario_id) REFERENCES usuarios (id)
);

CREATE INDEX idx_auditoria_eliminacion_usuario_usuario
    ON auditoria_eliminacion_usuario (usuario_id);
