-- Baseline del esquema existente, generado a mano leyendo cada @Entity en src/main/java
-- (no hay una instancia de Postgres corriendo en este entorno para hacer un dump real).
-- Con spring.flyway.baseline-on-migrate=true y spring.flyway.baseline-version=1, una base
-- de dev/prod ya existente (creada hoy por ddl-auto=update) se marca como si ya estuviera
-- en V1 sin volver a ejecutar este script; solo una base nueva/vacía lo ejecuta de verdad.
--
-- usuarios y establecimientos tienen una dependencia circular (usuarios.establecimiento_id
-- -> establecimientos, establecimientos.dueno_id -> usuarios), por eso la FK de
-- usuarios.establecimiento_id se agrega recién al final, con ALTER TABLE.

-- =========================================================================
-- usuarios
-- =========================================================================
CREATE TABLE usuarios (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email                VARCHAR(255) NOT NULL,
    password             VARCHAR(255) NOT NULL,
    nombre               VARCHAR(255) NOT NULL,
    telefono             VARCHAR(255),
    rol                  VARCHAR(255) NOT NULL,
    plan_suscripcion     VARCHAR(255),
    fecha_creacion       TIMESTAMP NOT NULL,
    is_active            BOOLEAN NOT NULL,
    email_verified       BOOLEAN NOT NULL,
    fecha_fin_prueba     TIMESTAMP,
    telefono_verificado  BOOLEAN NOT NULL,
    token_version        INTEGER NOT NULL,
    establecimiento_id   BIGINT,
    CONSTRAINT uk_usuarios_email UNIQUE (email)
);

-- =========================================================================
-- establecimientos
-- =========================================================================
CREATE TABLE establecimientos (
    id                                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre                             VARCHAR(255) NOT NULL,
    direccion                          VARCHAR(255) NOT NULL,
    latitud                            DOUBLE PRECISION NOT NULL,
    longitud                           DOUBLE PRECISION NOT NULL,
    requiere_sena                      BOOLEAN NOT NULL,
    is_active                          BOOLEAN NOT NULL,
    horas_cancelacion_antes_partido    INTEGER NOT NULL,
    minutos_gracia_cancelacion         INTEGER NOT NULL,
    dueno_id                           BIGINT NOT NULL,
    CONSTRAINT fk_establecimientos_dueno FOREIGN KEY (dueno_id) REFERENCES usuarios (id)
);

ALTER TABLE usuarios
    ADD CONSTRAINT fk_usuarios_establecimiento FOREIGN KEY (establecimiento_id) REFERENCES establecimientos (id);

-- =========================================================================
-- usuario_permisos (@ElementCollection de Usuario.permisos)
-- =========================================================================
CREATE TABLE usuario_permisos (
    usuario_id  BIGINT NOT NULL,
    permiso     VARCHAR(255) NOT NULL,
    CONSTRAINT fk_usuario_permisos_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id)
);

-- =========================================================================
-- codigos_verificacion
-- =========================================================================
CREATE TABLE codigos_verificacion (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email                VARCHAR(255) NOT NULL,
    codigo               VARCHAR(255) NOT NULL,
    telefono_pendiente   VARCHAR(255) NOT NULL,
    fecha_expiracion     TIMESTAMP NOT NULL,
    intentos             INTEGER NOT NULL,
    CONSTRAINT uk_codigos_verificacion_email UNIQUE (email)
);

-- =========================================================================
-- tokens_verificacion_email
-- =========================================================================
CREATE TABLE tokens_verificacion_email (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email              VARCHAR(255) NOT NULL,
    token              VARCHAR(255) NOT NULL,
    fecha_expiracion   TIMESTAMP NOT NULL,
    CONSTRAINT uk_tokens_verificacion_email_token UNIQUE (token)
);

-- =========================================================================
-- horarios_atencion
-- =========================================================================
CREATE TABLE horarios_atencion (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dia_semana          VARCHAR(255) NOT NULL,
    hora_apertura       TIME NOT NULL,
    hora_cierre         TIME NOT NULL,
    establecimiento_id  BIGINT NOT NULL,
    CONSTRAINT fk_horarios_atencion_establecimiento FOREIGN KEY (establecimiento_id) REFERENCES establecimientos (id)
);

-- =========================================================================
-- canchas
-- =========================================================================
CREATE TABLE canchas (
    id                            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre                        VARCHAR(255) NOT NULL,
    capacidad                     INTEGER NOT NULL,
    is_active                     BOOLEAN NOT NULL,
    canchas_necesarias            INTEGER,
    precio_base                   NUMERIC(38,2) NOT NULL,
    monto_sena                    NUMERIC(38,2) NOT NULL,
    establecimiento_id            BIGINT NOT NULL,
    permite_inicio_media_hora     BOOLEAN,
    CONSTRAINT fk_canchas_establecimiento FOREIGN KEY (establecimiento_id) REFERENCES establecimientos (id)
);

-- =========================================================================
-- cancha_deportes (@ElementCollection de Cancha.deportes)
-- =========================================================================
CREATE TABLE cancha_deportes (
    cancha_id  BIGINT NOT NULL,
    deporte    VARCHAR(255) NOT NULL,
    CONSTRAINT fk_cancha_deportes_cancha FOREIGN KEY (cancha_id) REFERENCES canchas (id)
);

-- =========================================================================
-- cancha_duraciones (@ElementCollection de Cancha.duracionesPermitidas)
-- =========================================================================
CREATE TABLE cancha_duraciones (
    cancha_id          BIGINT NOT NULL,
    duracion_minutos   INTEGER,
    CONSTRAINT fk_cancha_duraciones_cancha FOREIGN KEY (cancha_id) REFERENCES canchas (id)
);

-- =========================================================================
-- cancha_precios_duracion (@ElementCollection Map de Cancha.preciosPorDuracion)
-- =========================================================================
CREATE TABLE cancha_precios_duracion (
    cancha_id          BIGINT NOT NULL,
    duracion_minutos   INTEGER,
    precio             NUMERIC(38,2),
    CONSTRAINT fk_cancha_precios_duracion_cancha FOREIGN KEY (cancha_id) REFERENCES canchas (id)
);

-- =========================================================================
-- cancha_composicion (@ManyToMany Cancha.canchasFisicas)
-- =========================================================================
CREATE TABLE cancha_composicion (
    cancha_logica_id  BIGINT NOT NULL,
    cancha_fisica_id  BIGINT NOT NULL,
    CONSTRAINT fk_cancha_composicion_logica FOREIGN KEY (cancha_logica_id) REFERENCES canchas (id),
    CONSTRAINT fk_cancha_composicion_fisica FOREIGN KEY (cancha_fisica_id) REFERENCES canchas (id)
);

-- =========================================================================
-- tarifas
-- =========================================================================
CREATE TABLE tarifas (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cancha_id    BIGINT NOT NULL,
    dia_semana   VARCHAR(255) NOT NULL,
    hora_inicio  TIME NOT NULL,
    hora_fin     TIME NOT NULL,
    precio       NUMERIC(38,2) NOT NULL,
    CONSTRAINT fk_tarifas_cancha FOREIGN KEY (cancha_id) REFERENCES canchas (id)
);

-- =========================================================================
-- tarifa_precios_duracion (@ElementCollection Map de Tarifa.preciosPorDuracion)
-- =========================================================================
CREATE TABLE tarifa_precios_duracion (
    tarifa_id          BIGINT NOT NULL,
    duracion_minutos   INTEGER,
    precio             NUMERIC(38,2),
    CONSTRAINT fk_tarifa_precios_duracion_tarifa FOREIGN KEY (tarifa_id) REFERENCES tarifas (id)
);

-- =========================================================================
-- bloqueos_cancha
-- =========================================================================
CREATE TABLE bloqueos_cancha (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cancha_id      BIGINT NOT NULL,
    fecha_inicio   TIMESTAMP NOT NULL,
    fecha_fin      TIMESTAMP NOT NULL,
    motivo         VARCHAR(255),
    CONSTRAINT fk_bloqueos_cancha_cancha FOREIGN KEY (cancha_id) REFERENCES canchas (id)
);

-- =========================================================================
-- bloqueos_jugador
-- =========================================================================
CREATE TABLE bloqueos_jugador (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    establecimiento_id   BIGINT NOT NULL,
    jugador_id           BIGINT NOT NULL,
    motivo               VARCHAR(255),
    fecha_bloqueo        TIMESTAMP NOT NULL,
    CONSTRAINT uk_bloqueos_jugador_establecimiento_jugador UNIQUE (establecimiento_id, jugador_id),
    CONSTRAINT fk_bloqueos_jugador_establecimiento FOREIGN KEY (establecimiento_id) REFERENCES establecimientos (id),
    CONSTRAINT fk_bloqueos_jugador_jugador FOREIGN KEY (jugador_id) REFERENCES usuarios (id)
);

-- =========================================================================
-- dias_no_laborables
-- =========================================================================
CREATE TABLE dias_no_laborables (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha                DATE NOT NULL,
    motivo               VARCHAR(255),
    establecimiento_id   BIGINT NOT NULL,
    CONSTRAINT fk_dias_no_laborables_establecimiento FOREIGN KEY (establecimiento_id) REFERENCES establecimientos (id)
);

-- =========================================================================
-- reservas
-- =========================================================================
CREATE TABLE reservas (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    jugador_id                BIGINT,
    cancha_id                 BIGINT NOT NULL,
    deporte_seleccionado      VARCHAR(255) NOT NULL,
    nombre_cliente_manual     VARCHAR(255),
    telefono_cliente_manual   VARCHAR(255),
    fecha_hora_inicio         TIMESTAMP NOT NULL,
    fecha_hora_fin            TIMESTAMP NOT NULL,
    estado                    VARCHAR(255) NOT NULL,
    precio_total              NUMERIC(38,2) NOT NULL,
    sena_pagada                NUMERIC(38,2) NOT NULL,
    fecha_creacion            TIMESTAMP NOT NULL,
    expira_en                 TIMESTAMP,
    metodo_pago               VARCHAR(255),
    version                   BIGINT NOT NULL,
    CONSTRAINT fk_reservas_jugador FOREIGN KEY (jugador_id) REFERENCES usuarios (id),
    CONSTRAINT fk_reservas_cancha FOREIGN KEY (cancha_id) REFERENCES canchas (id)
);

-- =========================================================================
-- feedbacks
-- =========================================================================
CREATE TABLE feedbacks (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reserva_id       BIGINT NOT NULL,
    puntuacion       INTEGER NOT NULL,
    comentario       VARCHAR(1000),
    destacado        BOOLEAN NOT NULL,
    fecha_creacion   TIMESTAMP NOT NULL,
    CONSTRAINT uk_feedbacks_reserva UNIQUE (reserva_id),
    CONSTRAINT fk_feedbacks_reserva FOREIGN KEY (reserva_id) REFERENCES reservas (id)
);

-- =========================================================================
-- productos_buffet
-- =========================================================================
CREATE TABLE productos_buffet (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre               VARCHAR(255) NOT NULL,
    descripcion          VARCHAR(255),
    precio               NUMERIC(38,2) NOT NULL,
    stock                INTEGER NOT NULL,
    establecimiento_id   BIGINT NOT NULL,
    CONSTRAINT fk_productos_buffet_establecimiento FOREIGN KEY (establecimiento_id) REFERENCES establecimientos (id)
);

-- =========================================================================
-- ventas_buffet
-- =========================================================================
CREATE TABLE ventas_buffet (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_hora           TIMESTAMP NOT NULL,
    total                NUMERIC(38,2) NOT NULL,
    estado               VARCHAR(255) NOT NULL,
    establecimiento_id   BIGINT NOT NULL,
    reserva_id           BIGINT,
    CONSTRAINT fk_ventas_buffet_establecimiento FOREIGN KEY (establecimiento_id) REFERENCES establecimientos (id),
    CONSTRAINT fk_ventas_buffet_reserva FOREIGN KEY (reserva_id) REFERENCES reservas (id)
);

-- =========================================================================
-- detalles_venta
-- =========================================================================
CREATE TABLE detalles_venta (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cantidad              INTEGER NOT NULL,
    subtotal              NUMERIC(38,2) NOT NULL,
    venta_id              BIGINT NOT NULL,
    producto_buffet_id    BIGINT NOT NULL,
    CONSTRAINT fk_detalles_venta_venta FOREIGN KEY (venta_id) REFERENCES ventas_buffet (id),
    CONSTRAINT fk_detalles_venta_producto FOREIGN KEY (producto_buffet_id) REFERENCES productos_buffet (id)
);

-- =========================================================================
-- dispositivo_caja
-- =========================================================================
CREATE TABLE dispositivo_caja (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    establecimiento_id   BIGINT NOT NULL,
    label                VARCHAR(255) NOT NULL,
    token_hash           VARCHAR(255) NOT NULL,
    activo               BOOLEAN NOT NULL,
    creado_por_id        BIGINT NOT NULL,
    created_at           TIMESTAMP NOT NULL,
    last_used_at         TIMESTAMP,
    CONSTRAINT uk_dispositivo_caja_token_hash UNIQUE (token_hash),
    CONSTRAINT fk_dispositivo_caja_establecimiento FOREIGN KEY (establecimiento_id) REFERENCES establecimientos (id),
    CONSTRAINT fk_dispositivo_caja_creado_por FOREIGN KEY (creado_por_id) REFERENCES usuarios (id)
);

-- =========================================================================
-- codigo_emparejamiento_caja
-- =========================================================================
CREATE TABLE codigo_emparejamiento_caja (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_hash          VARCHAR(255) NOT NULL,
    establecimiento_id   BIGINT NOT NULL,
    label                VARCHAR(255),
    creado_por_id        BIGINT NOT NULL,
    expira_en            TIMESTAMP NOT NULL,
    usado                BOOLEAN NOT NULL,
    created_at           TIMESTAMP NOT NULL,
    CONSTRAINT uk_codigo_emparejamiento_caja_codigo_hash UNIQUE (codigo_hash),
    CONSTRAINT fk_codigo_emparejamiento_caja_establecimiento FOREIGN KEY (establecimiento_id) REFERENCES establecimientos (id),
    CONSTRAINT fk_codigo_emparejamiento_caja_creado_por FOREIGN KEY (creado_por_id) REFERENCES usuarios (id)
);

-- =========================================================================
-- registro_auditoria_empleados
-- =========================================================================
CREATE TABLE registro_auditoria_empleados (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empleado_id            BIGINT,
    actor_id               BIGINT,
    establecimiento_id     BIGINT NOT NULL,
    accion                 VARCHAR(255) NOT NULL,
    entidad_afectada_id    BIGINT,
    exitoso                BOOLEAN NOT NULL,
    detalle                VARCHAR(500),
    fecha_hora             TIMESTAMP NOT NULL,
    CONSTRAINT fk_registro_auditoria_empleado FOREIGN KEY (empleado_id) REFERENCES usuarios (id),
    CONSTRAINT fk_registro_auditoria_establecimiento FOREIGN KEY (establecimiento_id) REFERENCES establecimientos (id)
);

-- =========================================================================
-- solicitudes_idempotentes
-- =========================================================================
CREATE TABLE solicitudes_idempotentes (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clave                       VARCHAR(255) NOT NULL,
    usuario_email               VARCHAR(255) NOT NULL,
    metodo_http                 VARCHAR(255) NOT NULL,
    path                        VARCHAR(255) NOT NULL,
    body_hash                   VARCHAR(64) NOT NULL,
    status_respuesta            INTEGER,
    content_type_respuesta      VARCHAR(255),
    cuerpo_respuesta            TEXT,
    fecha_creacion              TIMESTAMP NOT NULL,
    fecha_completado            TIMESTAMP,
    CONSTRAINT uk_solicitudes_idempotentes_clave_usuario_email UNIQUE (clave, usuario_email)
);

CREATE INDEX idx_solicitudes_idempotentes_fecha_creacion ON solicitudes_idempotentes (fecha_creacion);
