-- =============================================================================
-- V20 — Cola de reintento para emails que fallaron al enviarse
--
-- Hasta ahora, si Resend fallaba, la excepción subía desde el listener @Async
-- (AFTER_COMMIT), la logueaba AsyncConfig.getAsyncUncaughtExceptionHandler y el
-- email se perdía para siempre. Para verificación de registro y recuperación de
-- contraseña eso deja al usuario sin poder avanzar, con el único recurso de
-- volver a pedirlo (limitado a 1/min por RegistroVerificacionService).
--
-- Se guarda el cuerpo YA RENDERIZADO, no el evento que lo originó: el reintento
-- manda exactamente lo mismo que falló, sin depender de que los datos de origen
-- (token, usuario, reserva) sigan existiendo ni de re-renderizar una plantilla
-- que pudo cambiar en el medio.
--
-- UNIQUE (destinatario, asunto): el asunto funciona como discriminador de
-- plantilla, porque cada listener lo pasa como constante (ASUNTO_VERIFICACION,
-- ASUNTO_RECUPERACION, etc.). No es cosmético — es una regla de corrección:
-- RegistroVerificacionService.iniciarRegistro borra el token anterior y crea uno
-- nuevo, así que si el primer email quedó encolado y el usuario vuelve a pedirlo,
-- reintentar el viejo mandaría un link con un token que ya no existe. Con esta
-- clave, un reencolado PISA el cuerpo anterior y siempre se reintenta el vigente.
-- =============================================================================

CREATE TABLE emails_pendientes (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    destinatario         VARCHAR(255) NOT NULL,
    asunto               VARCHAR(255) NOT NULL,
    cuerpo_html          TEXT NOT NULL,
    estado               VARCHAR(20) NOT NULL,
    intentos             INTEGER NOT NULL DEFAULT 0,
    ultimo_error         VARCHAR(500),
    fecha_creacion       TIMESTAMP NOT NULL,
    fecha_ultimo_intento TIMESTAMP,
    CONSTRAINT uk_emails_pendientes_destinatario_asunto UNIQUE (destinatario, asunto),
    CONSTRAINT ck_emails_pendientes_estado CHECK (estado IN ('PENDIENTE', 'ERROR'))
);

-- El job de reintento busca por estado + intentos y ordena por antigüedad; este
-- índice parcial cubre exactamente esa consulta y deja afuera las filas en ERROR,
-- que ya no se reintentan y sólo quedan para inspección manual.
CREATE INDEX idx_emails_pendientes_a_reintentar
    ON emails_pendientes (fecha_creacion)
    WHERE estado = 'PENDIENTE';
