-- =============================================================================
-- V22 — Auditoría de degradación de plan (TRIAL vencido -> FREE)
--
-- Tabla nueva y desacoplada de registro_auditoria_empleados (empleado/model): esa tabla
-- exige un establecimiento no-nulo por fila y no encaja acá, porque un OWNER en TRIAL puede
-- no tener ningún establecimiento todavía cuando se le vence la prueba. Mismo criterio que
-- V15 (auditoria_eliminacion_usuario) para el mismo tipo de problema.
-- =============================================================================

CREATE TABLE auditoria_degradacion_plan (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id   BIGINT NOT NULL,
    fecha_hora   TIMESTAMP NOT NULL,
    detalle      VARCHAR(500),
    CONSTRAINT fk_auditoria_degradacion_plan_usuario
        FOREIGN KEY (usuario_id) REFERENCES usuarios (id)
);

CREATE INDEX idx_auditoria_degradacion_plan_usuario
    ON auditoria_degradacion_plan (usuario_id);
