-- La REGLA de un turno fijo semanal. Las ocurrencias siguen viviendo en `reservas` y
-- apuntan acá con turno_fijo_id: la regla existe para poder renovar y cancelar la serie
-- como unidad, no para reemplazar a las reservas.
CREATE TABLE turnos_fijos (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cancha_id               BIGINT       NOT NULL,
    deporte_seleccionado    VARCHAR(255) NOT NULL,
    dia_semana              VARCHAR(255) NOT NULL,
    hora_inicio             TIME         NOT NULL,
    hora_fin                TIME         NOT NULL,
    fecha_inicio_periodo    DATE         NOT NULL,
    fecha_fin_periodo       DATE         NOT NULL,
    jugador_id              BIGINT,
    nombre_cliente_manual   VARCHAR(255),
    telefono_cliente_manual VARCHAR(255),
    estado                  VARCHAR(255) NOT NULL,
    cancelado_desde         DATE,
    renovado_desde_id       BIGINT,
    fecha_creacion          TIMESTAMP    NOT NULL,
    version                 BIGINT       NOT NULL,
    CONSTRAINT fk_turnos_fijos_cancha   FOREIGN KEY (cancha_id)         REFERENCES canchas (id),
    CONSTRAINT fk_turnos_fijos_jugador  FOREIGN KEY (jugador_id)        REFERENCES usuarios (id),
    CONSTRAINT fk_turnos_fijos_renovado FOREIGN KEY (renovado_desde_id) REFERENCES turnos_fijos (id),
    -- El horario vive sobre una sola fecha (LocalTime, sin 24:00), igual que cada ocurrencia.
    CONSTRAINT chk_turnos_fijos_horas CHECK (hora_inicio < hora_fin),
    CONSTRAINT chk_turnos_fijos_periodo CHECK (fecha_inicio_periodo <= fecha_fin_periodo),
    -- Impide el estado a medias: una serie cancelada siempre dice desde cuándo.
    CONSTRAINT chk_turnos_fijos_cancelacion CHECK (
            (estado = 'ACTIVO'    AND cancelado_desde IS NULL)
         OR (estado = 'CANCELADO' AND cancelado_desde IS NOT NULL))
);

-- Una serie se renueva UNA sola vez: sin esto, dos clicks seguidos en "Renovar" crean dos
-- series idénticas y la segunda recién falla por solapamiento, con un mensaje que no le
-- dice nada al dueño.
CREATE UNIQUE INDEX uk_turnos_fijos_renovado_desde
    ON turnos_fijos (renovado_desde_id)
    WHERE renovado_desde_id IS NOT NULL;

CREATE INDEX idx_turnos_fijos_cancha ON turnos_fijos (cancha_id);

ALTER TABLE reservas ADD COLUMN turno_fijo_id BIGINT;
ALTER TABLE reservas ADD CONSTRAINT fk_reservas_turno_fijo
    FOREIGN KEY (turno_fijo_id) REFERENCES turnos_fijos (id);

-- Parcial: la enorme mayoría de las reservas no son de turno fijo y no tiene sentido
-- indexarlas.
CREATE INDEX idx_reservas_turno_fijo ON reservas (turno_fijo_id)
    WHERE turno_fijo_id IS NOT NULL;
