-- Tabla para el flujo de recuperación de contraseña (Fase 2): token opaco + código de 6
-- dígitos, mismo diseño que tokens_verificacion_email (V1) + su columna de intentos (V2),
-- pero como tabla propia porque el ciclo de vida (creación, expiración, borrado) es
-- independiente del de la verificación de registro.

CREATE TABLE tokens_recuperacion_password (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email              VARCHAR(255) NOT NULL,
    token              VARCHAR(255) NOT NULL,
    codigo             VARCHAR(255) NOT NULL,
    fecha_expiracion   TIMESTAMP NOT NULL,
    intentos           INTEGER NOT NULL,
    CONSTRAINT uk_tokens_recuperacion_password_token UNIQUE (token)
);
