ALTER TABLE ventas_buffet ADD COLUMN metodo_pago VARCHAR(255);
UPDATE ventas_buffet SET metodo_pago = 'EFECTIVO' WHERE metodo_pago IS NULL;
ALTER TABLE ventas_buffet ALTER COLUMN metodo_pago SET NOT NULL;

-- =========================================================================
-- gastos: la tabla nunca se creó vía Flyway (el módulo se agregó sin su
-- propia migración) — se crea acá para que esta migración sea autoconsistente
-- sin importar si la tabla ya existe en el entorno de destino.
-- =========================================================================
CREATE TABLE IF NOT EXISTS gastos (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    establecimiento_id  BIGINT NOT NULL,
    fecha               DATE NOT NULL,
    monto               NUMERIC(38,2) NOT NULL,
    categoria           VARCHAR(255) NOT NULL,
    descripcion         VARCHAR(255) NOT NULL,
    comprobante_url     VARCHAR(255),
    usuario_registro_id BIGINT NOT NULL,
    fecha_creacion      TIMESTAMP NOT NULL,
    CONSTRAINT fk_gastos_establecimiento FOREIGN KEY (establecimiento_id) REFERENCES establecimientos (id),
    CONSTRAINT fk_gastos_usuario_registro FOREIGN KEY (usuario_registro_id) REFERENCES usuarios (id)
);

ALTER TABLE gastos ADD COLUMN IF NOT EXISTS metodo_pago VARCHAR(255);
UPDATE gastos SET metodo_pago = 'EFECTIVO' WHERE metodo_pago IS NULL;
ALTER TABLE gastos ALTER COLUMN metodo_pago SET NOT NULL;
