ALTER TABLE ventas_buffet ADD COLUMN metodo_pago VARCHAR(255);
UPDATE ventas_buffet SET metodo_pago = 'EFECTIVO' WHERE metodo_pago IS NULL;
ALTER TABLE ventas_buffet ALTER COLUMN metodo_pago SET NOT NULL;

-- =========================================================================
-- gastos: la tabla nunca se creó vía Flyway (el módulo se agregó sin su
-- propia migración) — se crea acá para que esta migración sea autoconsistente
-- sin importar si la tabla ya existe en el entorno de destino.
-- =========================================================================
CREATE TABLE IF NOT EXISTS gastos (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    establecimiento_id  BIGINT NOT NULL,
    fecha               DATE NOT NULL,
    monto               NUMERIC(38,2) NOT NULL,
    categoria           VARCHAR(255) NOT NULL,
    descripcion         VARCHAR(255) NOT NULL,
    comprobante_url     VARCHAR(255),
    usuario_registro_id BIGINT NOT NULL,
    fecha_creacion      TIMESTAMP NOT NULL,
    CONSTRAINT fk_gastos_establecimiento FOREIGN KEY (establecimiento_id) REFERENCES establecimientos (id),
    CONSTRAINT fk_gastos_usuario_registro FOREIGN KEY (usuario_registro_id) REFERENCES usuarios (id)
);

ALTER TABLE gastos ADD COLUMN IF NOT EXISTS metodo_pago VARCHAR(255);
UPDATE gastos SET metodo_pago = 'EFECTIVO' WHERE metodo_pago IS NULL;
ALTER TABLE gastos ALTER COLUMN metodo_pago SET NOT NULL;

-- =========================================================================
-- turno_caja / movimiento_caja
-- =========================================================================
CREATE TABLE turno_caja (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    establecimiento_id        BIGINT NOT NULL,
    dispositivo_caja_id       BIGINT,
    usuario_apertura_id       BIGINT NOT NULL,
    fecha_apertura            TIMESTAMP NOT NULL,
    fondo_inicial             NUMERIC(38,2) NOT NULL,
    estado                    VARCHAR(255) NOT NULL,
    fecha_cierre              TIMESTAMP,
    usuario_cierre_id         BIGINT,
    saldo_teorico_efectivo    NUMERIC(38,2),
    saldo_real_contado        NUMERIC(38,2),
    diferencia                NUMERIC(38,2),
    observaciones             VARCHAR(1000),
    CONSTRAINT fk_turno_caja_establecimiento FOREIGN KEY (establecimiento_id) REFERENCES establecimientos (id),
    CONSTRAINT fk_turno_caja_dispositivo FOREIGN KEY (dispositivo_caja_id) REFERENCES dispositivo_caja (id),
    CONSTRAINT fk_turno_caja_usuario_apertura FOREIGN KEY (usuario_apertura_id) REFERENCES usuarios (id),
    CONSTRAINT fk_turno_caja_usuario_cierre FOREIGN KEY (usuario_cierre_id) REFERENCES usuarios (id)
);

-- Un solo turno ABIERTO por establecimiento, reforzado a nivel DB además del chequeo en el service.
CREATE UNIQUE INDEX uk_turno_caja_abierto_por_establecimiento
    ON turno_caja (establecimiento_id)
    WHERE estado = 'ABIERTO';

CREATE INDEX idx_turno_caja_establecimiento ON turno_caja (establecimiento_id);

-- movimiento_caja
CREATE TABLE movimiento_caja (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    turno_caja_id     BIGINT NOT NULL,
    tipo              VARCHAR(255) NOT NULL,
    origen            VARCHAR(255) NOT NULL,
    metodo_pago       VARCHAR(255) NOT NULL,
    monto             NUMERIC(38,2) NOT NULL,
    descripcion       VARCHAR(500),
    referencia_id     BIGINT,
    fecha_hora        TIMESTAMP NOT NULL,
    usuario_id        BIGINT NOT NULL,
    CONSTRAINT fk_movimiento_caja_turno FOREIGN KEY (turno_caja_id) REFERENCES turno_caja (id),
    CONSTRAINT fk_movimiento_caja_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id)
);

CREATE INDEX idx_movimiento_caja_turno ON movimiento_caja (turno_caja_id);
